image:
  repository: partofaplan/cafe-lean
  tag: 0.1.3
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  # Default to sslip.io pointing to localhost; override per environment
  host: cafe-lean.192.168.5.78.sslip.io
  annotations: {}
  tls:
    enabled: false
    secretName: ""

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}
affinity: {}
tolerations: []

env:
  # Additional environment variables for the container
  # MAX_VOTES: "3"
  {}

