name: Build Docker Image (latest)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (tag as latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: cafe-lean:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

